base/urls.py
from django.conf.urls import url, include
from .views import (
    Inicio, 
    TerminosCondicionesFormView, 
    TerminosCondicionesView, 
    TerminosCondicionesAPIView
)
from utils.views import ResetPasswordViewSet, ChangePasswordViewSet

urlpatterns = [
    url(r'^$', Inicio.as_view(), name = "inicio"),
    url(r'^terminos-update/$', TerminosCondicionesFormView.as_view(), name = "update-terminos"),
    url(r'^terminos/$', TerminosCondicionesView.as_view(), name = "terminos"),
    url(r'^api/v1/terminos-api/$', TerminosCondicionesAPIView.as_view(), name = "terminos-api"),
    url(r'^api/v1/reset-password/', ResetPasswordViewSet.as_view()),
    url(r'^api/v1/change-password/', ChangePasswordViewSet.as_view()),
    
]

guaruras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views
from .views import obtain_user_auth_token, logout_user_auth_token, AdministratorPhone
from .router import router
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('usuarios.urls')),
    url(r'^servicios/', include('servicios.urls')),
    url(r'^alertas/', include('alertas.urls')),
    url(r'^api/v1/api-token-auth/', obtain_user_auth_token),
    url(r'^api/v1/api-token-logout/', logout_user_auth_token),
    url(r'^api/v1/get-admin-phone/', AdministratorPhone.as_view()),
    url(r'^api/v1/', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

servicios/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    #url(r'^register$', ServicioRegister.as_view(), name = "servicio_register"),
    url(r'^list$', ServicioList.as_view(), name = "servicio_list"),
    url(r'^update/(?P<pk>\d+)$', ServicioUpdate.as_view(), name = "servicio_update"),
    url(r'^guardias-list/(?P<id>\d+)$', GuardiasList.as_view(), name = "guardias_list"),
    url(r'^jefes/list/(?P<id>\d+)$', JefesChildList.as_view(), name = "guardias_asignados_list"),
    url(r'^jefes/asignar/(?P<id>\d+)$', JefesChildRegister.as_view(), name = "jefe_guardia_asignar"),
    url(r'^jefes/pariente/delete/(?P<pk>\d+)/(?P<hijo>\d+)$', ParienteDelete.as_view(), name = "pariente_delete"),
    url(r'^jefes/pariente/update/(?P<pk>\d+)/(?P<hijo>\d+)$', ParienteUpdate.as_view(), name = "pariente_update"),
]

servicios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from usuarios.models import Perfil

class Servicio(models.Model):
    """
    Clase que gestiona el modelo de servicios
    
    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 11-10-17
    """

    # Kilometraje máximo del servicio
    kilometraje = models.FloatField(validators=[MinValueValidator(1)])

    # Velocidad máxima del servicio
    velocidad = models.FloatField(null=True,validators=[MinValueValidator(1)])

    # Número de contacto en caso de emergencia
    telefono = models.CharField(max_length=15,)

    # Frecuencia de envío de información
    frecuencia_rastreo = models.IntegerField(validators=[MinValueValidator(1)])

    # Latitud inicial
    latitud_inicial = models.CharField(max_length=50)

    # Longitud inicial
    longitud_inicial = models.CharField(max_length=50)

    # Relación con el cliente
    cliente = models.OneToOneField(Perfil)

    def __str__(self):
        """!
        Metodo que muestra el objeto perfil como un str

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 13-10-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el str del perfil
        """
        return str(self.cliente.user.username)

class SeguridadServicio(models.Model):
    """
    Clase intermedia que asigna miembros de seguridad al servicio

    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 11-10-17
    """
    
    # Relación con el servicio
    servicio = models.ForeignKey(Servicio)

    # Relación con el guardia
    guardia = models.ForeignKey(Perfil)

    class Meta:
    	unique_together = ('servicio','guardia')

    def __str__(self):
        """!
        Metodo que muestra el objeto perfil como un str

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 13-10-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el str del perfil
        """
        return str(self.servicio.cliente.user.username+" - "+self.guardia.user.username)


class SeguridadJefeHijo(models.Model):
    """
    Clase intermedia que asigna miembros de seguridad a un servicio
    de un jefe de seguridad

    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 24-10-17
    """
    # Relación con el pariente
    pariente = models.ForeignKey(Perfil,related_name="seguridad_jefe_servicio_pariente")

    # Relación con el jefe de seguridad
    jefe_seguridad = models.ForeignKey(Perfil,related_name="seguridad_jefe_servicio_jefe")

    # Envío de notificaciones para el pariente
    notificacion = models.BooleanField(default=False)

    class Meta:
        unique_together = ('pariente','jefe_seguridad')

    def __str__(self):
        """!
        Metodo que muestra el objeto perfil como un str

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 13-10-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el str del perfil
        """
        return str("Jefe: "+self.jefe_seguridad.user.username+" - "+self.pariente.user.username)

alertas/forms.py
from django import forms
from usuarios.models import Perfil

class SendNotificationForm(forms.Form):
	"""!
	Clase del formulario de creación de notificaciones

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 18-10-2017
	"""
	# Listado de guardias 
	guardias_list = forms.ModelMultipleChoiceField(
		widget=forms.CheckboxSelectMultiple(),
		queryset = Perfil.objects.filter(user__groups=3).exclude(onesignal_id=None).all(),
		label='Listado de Guardias')

servicios/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory
from django.contrib.auth.models import User
from .models import Servicio, SeguridadJefeHijo
from usuarios.models import Perfil

class ServicioForm(ModelForm):
	"""!
	Clase del formulario de creación de servicios

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 01-03-2017
	"""

	def __init__(self, *args, **kwargs):
		"""!
		Metodo que sobreescribe cuando se inicializa el formulario

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 01-03-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@param args <b>{list}</b> Lista de los argumentos
		@param kwargs <b>{dict}</b> Diccionario con argumentos
		@return Retorna el formulario validado
		"""
		super(ServicioForm, self).__init__(*args, **kwargs)
		self.fields['kilometraje'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Límite de Kilométraje'})
		self.fields['velocidad'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Límite de velocidad'})
		self.fields['velocidad'].required = False
		self.fields['telefono'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Télefono'})
		self.fields['frecuencia_rastreo'].widget = forms.Select()
		self.fields['frecuencia_rastreo'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Frecuencia de Rastreo (mínutos)'})
		self.fields['frecuencia_rastreo'].widget.choices=(('','Seleccione un valor...'),('5','5'),('10','10'),('15','15'),('30','30'))
		self.fields['cliente'].queryset = Perfil.objects.filter(user__groups=2).all()
		self.fields['cliente'].widget.attrs.update({'class': 'form-control'})
		self.fields['cliente'].empty_label = "Seleccione un cliente..."
		# Latitud y Longitud
		self.fields['latitud_inicial'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Latitud','readonly':True})
		self.fields['longitud_inicial'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Longitud','readonly':True})

	# Listado de guardias 
	guardias = forms.ModelChoiceField(
		widget=forms.Select(attrs={'class':'form-control'}),
		queryset = Perfil.objects.filter(user__groups=3).all(),
		label="Jefe de Seguridad", empty_label = "Seleccione un jefe de seguridad..."
		)

	class Meta:
		model = Servicio
		fields = '__all__'
		# exclude = ('velocidad',)

class ServicioUpdateForm(ModelForm):
	"""!
	Clase del formulario de actualización de servicios

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 15-11-2017
	"""

	def __init__(self, *args, **kwargs):
		"""!
		Metodo que sobreescribe cuando se inicializa el formulario

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 01-03-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@param args <b>{list}</b> Lista de los argumentos
		@param kwargs <b>{dict}</b> Diccionario con argumentos
		@return Retorna el formulario validado
		"""
		super(ServicioUpdateForm, self).__init__(*args, **kwargs)
		self.fields['kilometraje'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Límite de Kilométraje'})
		self.fields['velocidad'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Límite de velocidad'})
		self.fields['velocidad'].required = False
		self.fields['telefono'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Télefono'})
		self.fields['frecuencia_rastreo'].widget = forms.Select()
		self.fields['frecuencia_rastreo'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Frecuencia de Rastreo (mínutos)'})
		self.fields['frecuencia_rastreo'].widget.choices=(('','Seleccione un valor...'),('5','5'),('10','10'),('15','15'),('30','30'))
		# Latitud y Longitud
		self.fields['latitud_inicial'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Latitud','readonly':True})
		self.fields['longitud_inicial'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Longitud','readonly':True})

	# Listado de guardias 
	guardias = forms.ModelChoiceField(
		widget=forms.Select(attrs={'class':'form-control'}),
		queryset = Perfil.objects.filter(user__groups=3).all(),
		label="Jefe de Seguridad", empty_label = "Seleccione un jefe de seguridad..."
		)

	class Meta:
		model = Servicio
		exclude = ('cliente',)



class AsignarGuardiaForm(ModelForm):
	"""!
	Clase del formulario para la asignación de guardias

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 24-10-2017
	"""

	def __init__(self, *args, **kwargs):
		"""!
		Metodo que sobreescribe cuando se inicializa el formulario

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 24-10-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@param args <b>{list}</b> Lista de los argumentos
		@param kwargs <b>{dict}</b> Diccionario con argumentos
		@return Retorna el formulario validado
		"""
		super(AsignarGuardiaForm, self).__init__(*args, **kwargs)
		self.fields['pariente'].widget.attrs.update({'class': 'form-control',
		'placeholder': 'Asignar paciente'})
		self.fields['pariente'].queryset = Perfil.objects.filter(user__groups__name="Cliente").all()
		self.fields['notificacion'].label = "¿Recibir notificaciones?"

	class Meta:
		model = SeguridadJefeHijo
		exclude = ('jefe_seguridad',)

class AsignarGuardiaExcludeForm(AsignarGuardiaForm):
	"""!
	Clase del formulario para la asignación de guardias

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 24-10-2017
	"""

	def __init__(self, *args, **kwargs):
		"""!
		Metodo que sobreescribe cuando se inicializa el formulario

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 24-10-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@param args <b>{list}</b> Lista de los argumentos
		@param kwargs <b>{dict}</b> Diccionario con argumentos
		@return Retorna el formulario validado
		"""
		super(AsignarGuardiaExcludeForm, self).__init__(*args, **kwargs)
		asignados = SeguridadJefeHijo.objects.values_list('pariente_id')
		self.fields['pariente'].queryset = Perfil.objects.exclude(id__in=asignados).filter(user__groups__name="Cliente").all()
		

AsignarGuardiaFormset = inlineformset_factory(Perfil,SeguridadJefeHijo, 
	form=AsignarGuardiaExcludeForm,
	extra=0,
	min_num=1, 
	validate_min=True, 
	fk_name="jefe_seguridad",
	fields=("pariente","notificacion")
	)

servicios/templates/guardias.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Guardias Asignados{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Guardias Asignados</h1><br/>
		{% if object_list %}
			<table class="table table-responsive table-striped">
				<thead>
					<tr >
						<th class="text-center">Nombre</th>
						<th class="text-center">Correo</th>
						<th class="text-center">Nombre de la Empresa</th>
						<th class="text-center">Opciones</th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
						<tr>
							<td>{{ object.guardia.user.username }}</td>
							<td>{{ object.guardia.user.email }}</td>
							<td>{{ object.guardia.nombre_empresa }}</td>
							<td><a href="{% url 'user_detail' object.guardia.pk %}">
								<i class="fa fa-search" aria-hidden="true"></i> Ver Perfil</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include 'base.paginator.html' with paginator=page_obj %}
		{% else %}
		    <div class="alert alert-warning" role="alert">
	            No tiene guardias asignados a este servicio
	        </div>
		{% endif %}
	</div>
	<a role="button" class="btn btn-secondary" href="{% url 'servicio_list' %}">Regresar</a>
{% endblock %}

servicios/templates/jefes.child.create.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Asignar Pariente{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Asignar Pariente</h1><hr>
		<form method="post">
			{% csrf_token %}
			{{ form.management_form }}
			{% for field in form %}
				{% if forloop.counter < 6 %}
					<div class="form-group row {% if field.errors %}is-invalid{% endif %}">
						<label for="{{ field.auto_id }}" class="col-form-label">
						{{ field.label }}
						</label>
						<div class="col-sm-9">
						{{ field }}
						</div>
						{% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
					</div><br/>
				{% endif %}
			{% endfor %}

			<div class="text-center">
				<a role="button" class="btn btn-secondary" href="{% url 'guardias_asignados_list' id %}">Regresar</a>
				<button type="submit" class="btn btn-success">Asignar</button>
			</div>
		</form>
	</div>
{% endblock %}
{% block extraJs %}
<script type="text/javascript">
	$('.form-group').formset({
		'prefix':'aisgnar-pariente',
		'addText': 'Agregar otro Pariente',
		'addIcon': '<i class="fa fa-plus-circle" aria-hidden="true">',
        'deleteText': 'Eliminar',
        'deleteIcon': '<i class="fa fa-minus" aria-hidden="true">'
    });
</script>
{% endblock %}

servicios/templates/jefes.child.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Parientes Asignados{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Parientes Asignados</h1><br/>
		<a role="button" class="btn btn-success" href="{% url 'jefe_guardia_asignar' id %}">Asignar nuevo pariente</a><br/><br/>
		{% if object_list %}
			<table class="table table-responsive table-striped">
				<thead>
					<tr >
						<th class="text-center">Nombre</th>
						<th class="text-center">Correo</th>
						<th class="text-center">Nombre de la Empresa</th>
						<th class="text-center" colspan="3">Opciones</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
						<tr>
							<td>{{ object.pariente.user.username }}</td>
							<td>{{ object.pariente.user.email }}</td>
							<td>{{ object.pariente.nombre_empresa }}</td>
							<td><a href="{% url 'user_detail' object.pariente.pk %}">
								<i class="fa fa-search" aria-hidden="true"></i> Ver Perfil</a>
							</td>
							<td><a href="{% url 'pariente_update' object.jefe_seguridad.id object.pariente.id %}">
								<i class="fa fa-pencil" aria-hidden="true"></i> Modificar</a>
							</td>
							<td>
								<a href="{% url 'pariente_delete' object.jefe_seguridad.id object.pariente.id %}">
									<i class="fa fa-minus-circle" aria-hidden="true"></i> 
								Eliminar</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include 'base.paginator.html' with paginator=page_obj %}
		{% else %}
		    <div class="alert alert-warning" role="alert">
	            No tiene parientes asignados
	        </div>
		{% endif %}
	</div>
	<a role="button" class="btn btn-secondary" href="{% url 'jefes_list' %}">Regresar</a>
{% endblock %}

servicios/templates/jefes.child.update.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Actualizar Pariente{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Actualizar Pariente</h1><hr>
		<form action="" method="post">
			{% csrf_token %}
			{% for field in form %}
				{% if forloop.counter < 5 %}
					<div class="form-group row {% if field.errors %}is-invalid{% endif %}">
						<label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">
						{{ field.label }}
						</label>
						<div class="col-sm-10">
						{{ field }}
						</div>
						{% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
					</div><br/>
				{% endif %}
			{% endfor %}

			<div class="text-center">
				<a role="button" class="btn btn-secondary" href="{% url 'guardias_asignados_list' pk %}">Regresar</a>
				<button type="submit" class="btn btn-primary">Actualizar</button>
			</div>
		</form>
	</div>
{% endblock %}

servicios/templates/pariente.delete.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Eliminar Pariente {% endblock %}
{% block content %}
	<div class="text-center">
	    <h1>Borrar pariente <b>{{object.pariente.user.username}}</b></h1><hr>
	    <form method="post">
	        {% csrf_token %}
	        <p>Si en realidad deseas borrar este registro da click en:</p>
	        <button type="submit" class="btn btn-danger">Borrar </button>
	    </form><br>
	    <a role="button" class="btn btn-info" href="{% url 'guardias_asignados_list' object.jefe_seguridad_id %}"> Regresar </a>
	</div>
{% endblock %}

servicios/templates/servicio.create.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Servicios{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Registrar nuevo servicio</h1><hr>
		<form action="{% url 'servicio_register' %}" method="post">
			{% csrf_token %}
			{% for field in form %}
				{% if forloop.counter < 5 %}
					<div class="form-group row {% if field.errors %}is-invalid{% endif %}">
						<label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">
						{{ field.label }}
						</label>
						<div class="col-sm-10">
						{{ field }}
						</div>
						{% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
					</div><br/>
				{% endif %}
			{% endfor %}
			<div class="form-group row">
				<div class="col-md-5">		
						{{ form.guardias_list }}
				</div>
				<div class="col-md-2">
					<a onclick="move_select_text('#id_guardias_list','#id_guardias')">
						<i class="fa fa-arrow-right" aria-hidden="true" style="cursor:pointer"></i>
					</a>
					<br/>
					<a onclick="move_select_text('#id_guardias','#id_guardias_list')">
						<i class="fa fa-arrow-left" aria-hidden="true" style="cursor:pointer"></i>
					</a>
				</div>
				<div class="col-md-5">
					{{ form.guardias }}
				</div>
			</div>

			<div class="text-center">
				<button type="submit" class="btn btn-success">Registrar</button>
			</div>
		</form>
	</div>
{% endblock %}

servicios/templates/servicio.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Listado de Servicios{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Listado de Servicios</h1><br/>
		{% if object_list %}
			<table class="table table-responsive table-striped">
				<thead>
					<tr >
						<th class="text-center">Límite de Kilometraje</th>
						<th class="text-center">Límite de Velocidad</th>
						<th class="text-center">Télefono de Contacto</th>
						<th class="text-center">Frecuencia de Rastreo</th>
						<th class="text-center">Cliente</th>
						<!-- <th class="text-center">Guardias Asignados</th> -->
						<th class="text-center">Editar</th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
						<tr>
							<td>{{ object.kilometraje }}</td>
							<td>{{ object.velocidad }}</td>
							<td>{{ object.telefono }}</td>
							<td>{{ object.frecuencia_rastreo }}</td>
							<td>{{ object.cliente.user.username }}</td>
							{% comment %}
							<!-- <td><a href="{% url 'guardias_list' object.pk %}">
								<i class="fa fa-search" aria-hidden="true"></i> Ver</a>
							</td> -->
							{% endcomment %}
							<td><a href="{% url 'servicio_update' object.pk %}">
								<i class="fa fa-edit" aria-hidden="true"></i> Editar</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include 'base.paginator.html' with paginator=page_obj %}
		{% else %}
		    <div class="alert alert-warning" role="alert">
	            No se encontraron registros de Servicios 
	        </div>
		{% endif %}
	</div>
{% endblock %}

servicios/templates/servicio.update.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Actualizar Servicio{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Actualizar servicio</h1><hr>
		<form action="" method="post">
			{% csrf_token %}
			{% for field in form %}
				{% if forloop.counter < 5 %}
					<div class="form-group row {% if field.errors %}is-invalid{% endif %}">
						<label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">
						{{ field.label }}
						</label>
						<div class="col-sm-10">
						{{ field }}
						</div>
						{% include 'base.forms.errors.html' with form_errors=field.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
					</div><br/>
				{% endif %}
			{% endfor %}
			<div class="form-group row {% if form.guardias.errors %}is-invalid{% endif %}">
				<label for="{{ form.guardias.auto_id }}" class="col-sm-2 col-form-label">
				{{ form.guardias.label }}
				</label>
				<div class="col-sm-10">
				{{ form.guardias }}
				</div>
				{% include 'base.forms.errors.html' with form_errors=form.guardias.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
			</div><br/>

			<div id="map" style="height: 400px;width: 100%;"></div>

	        <div class="row">
	          <div class="col-md-6 {% if form.latitud_inicial.errors %}is-invalid{% endif %}">
	              <label for="{{ form.latitud_inicial.auto_id }}" class="col-form-label">
	                {{ form.latitud_inicial.label }}
	              </label>
	              {{ form.latitud_inicial }}
	              {% include 'base.forms.errors.html' with form_errors=form.latitud_inicial.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
	          </div>
	          <div class="col-md-6 {% if form.longitud_inicial.errors %}is-invalid{% endif %}">
	              <label for="{{ form.longitud_inicial.auto_id }}" class="col-form-label">
	                {{ form.longitud_inicial.label }}
	              </label>
	              {{ form.longitud_inicial }}
	              {% include 'base.forms.errors.html' with form_errors=form.longitud_inicial.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
	          </div>
	        </div><br/>

			<div class="text-center">
				<a role="button" class="btn btn-secondary" href="{% url 'servicio_list' %}">Regresar</a>
				<button type="submit" class="btn btn-primary">Actualizar</button>
			</div>
		</form>
	</div>
{% endblock %}
{% block extraJs %}
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCB2JmjC8UmVNtWXAUIMkhYG1_xf0QKrzI"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      load_google_map(parseFloat($('#id_latitud_inicial').val()),parseFloat($('#id_longitud_inicial').val()));
    });
  </script>
{% endblock %}