base/urls.py
from django.conf.urls import url, include
from .views import (
    Inicio, 
    TerminosCondicionesFormView, 
    TerminosCondicionesView, 
    TerminosCondicionesAPIView
)
from utils.views import ResetPasswordViewSet, ChangePasswordViewSet

urlpatterns = [
    url(r'^$', Inicio.as_view(), name = "inicio"),
    url(r'^terminos-update/$', TerminosCondicionesFormView.as_view(), name = "update-terminos"),
    url(r'^terminos/$', TerminosCondicionesView.as_view(), name = "terminos"),
    url(r'^api/v1/terminos-api/$', TerminosCondicionesAPIView.as_view(), name = "terminos-api"),
    url(r'^api/v1/reset-password/', ResetPasswordViewSet.as_view()),
    url(r'^api/v1/change-password/', ChangePasswordViewSet.as_view()),
    
]

guaruras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views
from .views import obtain_user_auth_token, logout_user_auth_token, AdministratorPhone
from .router import router
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('usuarios.urls')),
    url(r'^servicios/', include('servicios.urls')),
    url(r'^alertas/', include('alertas.urls')),
    url(r'^api/v1/api-token-auth/', obtain_user_auth_token),
    url(r'^api/v1/api-token-logout/', logout_user_auth_token),
    url(r'^api/v1/get-admin-phone/', AdministratorPhone.as_view()),
    url(r'^api/v1/', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User

class TerminosCondiciones(models.Model):
    texto = models.TextField()

base/forms.py
from django import forms
from .models import TerminosCondiciones

class TerminosCondicionesForm(forms.Form):
    texto = forms.CharField(widget=forms.Textarea(
        attrs={
        'class':'form-control',
        'placeholder':'Texto',
        'rows':'20',
        }
    ))

base/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.contrib.auth.decorators import login_required
from base.models import TerminosCondiciones
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from .forms import TerminosCondicionesForm
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponseRedirect

def user_super_admin(function):
    def wrap(request, *args, **kwargs):

        user = request.user
        if user.is_superuser:
             return function(request, *args, **kwargs)
        else:
            return HttpResponseRedirect('/')

    wrap.__doc__=function.__doc__
    wrap.__name__=function.__name__
    return wrap


class Inicio(GroupRequiredMixin, LoginRequiredMixin, TemplateView):
    """!
    Clase de la vista inicial

    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 11-10-2017
    """
    template_name = "inicio.html"
    group_required = u"Administrador"

class TerminosCondicionesFormView(LoginRequiredMixin, FormView):
    """!
    Clase de la vista inicial

    @author Pablo Gonzalez (pdonaire1 at gmail)
    @date 11-10-2017
    """
    template_name = "terminos_condiciones.html"
    # group_required = u"Administrador"
    form_class = TerminosCondicionesForm
    success_url = '/terminos/'#reverse('terminos')

    def form_valid(self, form):
        obj =TerminosCondiciones.objects.get(id=1)
        obj.texto = form.cleaned_data['texto']
        obj.save()
        return super(TerminosCondicionesFormView, self).form_valid(form)

    def get_object(self, queryset=None):
        if TerminosCondiciones.objects.filter(id=1).exists():
            obj =TerminosCondiciones.objects.get(id=1)
        else:
            obj = TerminosCondiciones.objects.create(id=1, texto='')
        return obj

    def get_initial(self):
        context = super(TerminosCondicionesFormView, self).get_initial()
        context['texto'] = TerminosCondiciones.objects.get(id=1).texto
        print (context)
        return context
    def get_context_data(self, **kwargs):
        if TerminosCondiciones.objects.filter(id=1).exists():
            obj =TerminosCondiciones.objects.get(id=1)
        else:
            obj = TerminosCondiciones.objects.create(id=1, texto='')
        context = super(TerminosCondicionesFormView, self).get_context_data(**kwargs)
        context['texto'] = obj.texto
        return context
    
    @method_decorator(user_super_admin)
    def dispatch(self, *args, **kwargs):
        return super(TerminosCondicionesFormView, self).dispatch(*args, **kwargs)


class TerminosCondicionesView(TemplateView):
    template_name = "terminos.html"

    def get_context_data(self, **kwargs):
        context = super(TerminosCondicionesView, self).get_context_data(**kwargs)
        if TerminosCondiciones.objects.filter(id=1).exists():
            obj =TerminosCondiciones.objects.get(id=1)
        else:
            obj = TerminosCondiciones.objects.create(id=1, texto='')
        context['object'] = obj
        context['show_update'] = True if (self.request.user and self.request.user.is_superuser) else False
        return context


class TerminosCondicionesAPIView(APIView):
    """
    @author Pablo Gonzalez (pdonaire1 at gmail)
    @date 11-10-2017
    Muestra los terminos y condiciones del servicio
    """
    authentication_classes = ()
    permission_classes = ()

    def get(self, request, format=None):
        return Response({
            'texto': TerminosCondiciones.objects.get(id=1).texto
        })

base/templates/base.alert.msg.html
{% load i18n %}
{% for message in messages %}
    {% if message %}
        <div class="alert alert-success row" role="alert">
            {{message}}
        </div>
    {% endif %}
{% endfor %}

base/templates/base.footer.html
<nav class="navbar fixed-bottom navbar-dark bg-dark">
	<ul class="navbar-nav mx-auto">
		<li class="navbar-item"><a class="navbar-brand" href="#">Guaruras &copy; {% now 'Y' %}</a></li>
	</ul>
</nav>

base/templates/base.forms.errors.html
{% if form_errors %}
    <div class="error-notice">
        <div class="oaerror danger">
            <div class="row">
                <div class="{% if not col_title_error %}col-sm-3{% else %}{{ col_title_error }}{% endif %}">
                    <strong>Error</strong>
                </div>
                <div class="{% if not col_msg_error %}col-sm-9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>

        </div>
    </div>
{% endif %}

base/templates/base.modals.html
<div class="modal fade map_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    	<div id="map" style="height: 400px;width: 100%;"></div>
    </div>
  </div>
</div>

base/templates/base.navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="{% url 'inicio' %}">Guaruras</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Inicio">
        <a class="nav-link" href="{% url 'inicio' %}">
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">Inicio</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Usuarios">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
          <i class="fa fa-fw fa-user-o"></i>
          <span class="nav-link-text">Usuarios</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseComponents">
          <li>
            <a href="{% url 'register' %}">Registrar</a>
          </li>
          <li>
            <a href="{% url 'user_list' %}">Ver</a>
          </li>
        </ul>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Servicios">
        <a class="nav-link" href="{% url 'servicio_list' %}">
          <i class="fa fa-fw fa-coffee"></i>
          <span class="nav-link-text">Servicios</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Jefes de Seguridad">
        <a class="nav-link" href="{% url 'jefes_list' %}">
          <i class="fa fa-fw fa-user-circle"></i>
          <span class="nav-link-text">Jefes de Seguridad</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Alertas">
        <a class="nav-link" href="{% url 'alerta_all_list' %}">
          <i class="fa fa-fw fa-warning"></i>
          <span class="nav-link-text">Alertas</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mensajes">
        <a class="nav-link" href="{% url 'mensajes_list' %}">
          <i class="fa fa-fw fa-send"></i>
          <span class="nav-link-text">Mensajes</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Terminos y Condiciones">
        <a class="nav-link" href="{% url 'terminos' %}">
          <i class="fa fa-fw fa-file-text-o"></i>
          <span class="nav-link-text">Terminos y Condiciones</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        
        <li class="nav-item dropdown">
          
            {% if request.user.is_authenticated %}
              <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="alertsDropdown" style="left: -20%">
              <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
            </div>
            {% endif %}
          
        </li>
      </ul>
          <!-- {% if request.user.is_authenticated %}
           <ul class="navbar-nav mr mt-2 mt-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="user_option" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="user_option" style="margin-left: -70px;">
                <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
              </div>
            </li>
          </ul>
          {% else %}
            <ul class="navbar-nav mr mt-2 mt-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">Anónimo</a>
              </li>
            </ul>
          {% endif %} -->
    
  </div>
</nav>
        
        
        <!-- 
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'inicio' %}">Guaruras</a>
  <button class="navbar-toggler" role="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="usuarios" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Usuarios
          </a>
          <div class="dropdown-menu" aria-labelledby="usuarios">
            <a class="dropdown-item" href="{% url 'register' %}">Registrar</a>
            <a class="dropdown-item" href="{% url 'user_list' %}">Ver</a>
          </div>
        </li>
      </li>
      <li class="nav-item"><a class="nav-link" href="{% url 'servicio_list' %}">Servicios</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'jefes_list' %}">Jefes de Seguridad</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'alerta_all_list' %}">Alertas</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'mensajes_list' %}">Mensajes</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'terminos' %}">Terminos Y Condiciones</a></li>
    </ul>
    {% if request.user.is_authenticated %}
     <ul class="navbar-nav mr mt-2 mt-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="user_option" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="user_option" style="margin-left: -70px;">
          <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
        </div>
      </li>
    </ul>
    {% else %}
      <ul class="navbar-nav mr mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Anónimo</a>
        </li>
      </ul>
    {% endif %}
    </ul>
  </div>
</nav>
 -->

base/templates/base.paginator.html
<div class="row justify-content-md-center">
    <ul class="pagination text-center">
        {% if paginator.has_previous %}
            <li class="page-item">
                <span>
                    <a href="?page={{ paginator.previous_page_number }}" class="page-link">
                        <i class="fa fa-chevron-left" aria-hidden="true"></i> Anterior
                    </a>
                </span>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span>
                    <a href="#" class="page-link">
                        <i class="fa fa-chevron-left" aria-hidden="true"></i> Anterior
                    </a>
                </span>
            </li>
        {% endif %}
            <li>
                <span>Página {{ paginator.number }} de {{ paginator.paginator.num_pages }}.</span>
            </li>
        {% if paginator.has_next %}
            <li class="page-item">
                <span>
                    <a href="?page={{ paginator.next_page_number }}" class="page-link">
                        Siguiente <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                </span>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span>
                    <a href="#" class="page-link">
                        Siguiente <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                </span>
            </li>
        {% endif %}
    </ul>
</div>

base/templates/base.template.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    	<meta charset="utf-8">
        <meta name="author" content="dakonondevelopers">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="stylesheet" type="text/css" href="{% static 'plugins/bootstrap4/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link id="favicon" rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

        <!-- Bootstrap core CSS-->
        <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
        <!-- Custom fonts for this template-->
        <!-- <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
        <!-- Page level plugin CSS-->
        <!-- <link href="vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet"> -->
        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    	{% block extraCss %}{% endblock %}
        <title id="title-page">{% block title %}{% endblock %}</title>
    </head>
    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
    	{% include 'base.navbar.html' %}
        <!-- <div class="container"> -->
        <div class="content-wrapper">
            <div class="container-fluid">
              <!-- Breadcrumbs-->
              <!-- <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">My Dashboard</li>
              </ol> -->
                {% include 'base.alert.msg.html' %}
        <!-- </div> -->
                {% block superContent %}
                    <div class="container" id="content">
                        {% block content %}{% endblock %}
                    </div>
                {%endblock%}
            </div>
        </div>
        <!-- <footer>
    		{% include 'base.footer.html' %}
    	</footer> -->
    	<script type="text/javascript" src="{% static 'plugins/bootstrap4/js/jquery-3.2.1.min.js' %}"></script>
    	<script type="text/javascript" src="{% static 'plugins/bootstrap4/js/popper.min.js' %}"></script>
    	<script type="text/javascript" src="{% static 'plugins/bootstrap4/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-datepicker//js/bootstrap-datepicker.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-datepicker//js/bootstrap-datepicker.es.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/funciones.js' %}"></script>

        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>
        <script src="{% static 'js/sb-admin.min.js' %}"></script>
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async='async'></script>
        {% if request.user.is_authenticated %}
            <script>
                // https://documentation.onesignal.com/v3.0/docs/web-push-sdk#section--addlistenerfornotificationopened-
                var OneSignal = window.OneSignal || [];
                    OneSignal.push(["init", {
                    appId: "84d86d4d-5c55-4653-9ff5-3eafd056cdd4",
                    autoRegister: true, /* Set to true to automatically prompt visitors */
                    notifyButton: {
                      enable: true /* Set to false to hide */
                    }
                }]);

                function receive_notification(){
                    document.getElementById("title-page").text="**ALERTA**";
                    document.getElementById("favicon").href="{% static 'img/alerta.png' %}";
                    var audio = new Audio("{% static 'sounds/alertasound.mp3' %}");
                    audio.play();
                }
                function notification_opened(){
                    document.getElementById("title-page").text=title;
                    document.getElementById("favicon").href="{% static 'img/favicon.png' %}";
                    window.location = "{% url 'alerta_all_list' %}"
                }
                var title = $("#title-page").text();
                setTimeout(function(){
                    // OneSignal.push(["addListenerForNotificationOpened", function(data) {
                    //     notification_opened();
                    // }]);
                    OneSignal.on(OneSignal.EVENTS.NOTIFICATION_CLICKED,function(evnt){
                        notification_opened();
                    });
                    OneSignal.on(OneSignal.EVENTS.NOTIFICATION_DISPLAYED,function(evnt){
                        console.log("notificacion recibida");
                        receive_notification()
                    });
                }, 1000)

            </script>
        {% endif %}
    	{% block extraJs %}{% endblock %}
    </body>
</html>

base/templates/inicio.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block title %}Inicio{% endblock %}
{% block content %}
	<h1 class="text-center">Bienvenidos a Guaruras</h1><hr/>
	<br/>
	<p>Tú sistema para seguimiento y gestión de alertas.</p>
	<br/>
{% endblock %}

base/templates/terminos.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block title %}Terminos y condiciones{% endblock %}
{% block content %}
	{% if show_update %}
		<a href="{% url 'update-terminos'%}">
			<i class="fa fa-edit" aria-hidden="true"></i>Editar</a>
	{% endif %}
	<br/>
		{{object.texto}}
	<br/>

{% endblock %}

base/templates/terminos_condiciones.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block title %}Terminos y condiciones{% endblock %}
{% block content %}
	<br/>
	<form action="" method="post">{% csrf_token %}
	    <div class="form-group row ">
	    	
		    <label for="texto" class="col-sm-2 col-form-label">
	            {{ form.texto.label }}
	        </label>
	        <div class="col-sm-10">
		        {{ form.texto }}
	        </div>
	    </div>
        <div class="text-center">
    		<button type="submit" class="btn btn-success">Actualizar</button>
    	</div>
	</form>
	<script type="text/javascript">
		setTimeout(function(){

			$('#id_texto')[0].value="{{texto}}"
		}, 1000)
	</script>
	<br/>
{% endblock %}