base/urls.py
from django.conf.urls import url, include
from .views import (
    Inicio, 
    TerminosCondicionesFormView, 
    TerminosCondicionesView, 
    TerminosCondicionesAPIView
)
from utils.views import ResetPasswordViewSet, ChangePasswordViewSet

urlpatterns = [
    url(r'^$', Inicio.as_view(), name = "inicio"),
    url(r'^terminos-update/$', TerminosCondicionesFormView.as_view(), name = "update-terminos"),
    url(r'^terminos/$', TerminosCondicionesView.as_view(), name = "terminos"),
    url(r'^api/v1/terminos-api/$', TerminosCondicionesAPIView.as_view(), name = "terminos-api"),
    url(r'^api/v1/reset-password/', ResetPasswordViewSet.as_view()),
    url(r'^api/v1/change-password/', ChangePasswordViewSet.as_view()),
    
]

guaruras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views
from .views import obtain_user_auth_token, logout_user_auth_token, AdministratorPhone
from .router import router
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('usuarios.urls')),
    url(r'^servicios/', include('servicios.urls')),
    url(r'^alertas/', include('alertas.urls')),
    url(r'^api/v1/api-token-auth/', obtain_user_auth_token),
    url(r'^api/v1/api-token-logout/', logout_user_auth_token),
    url(r'^api/v1/get-admin-phone/', AdministratorPhone.as_view()),
    url(r'^api/v1/', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.conf.urls import url
from django.contrib.auth.views import *
from .forms import PasswordResetForm, PasswordConfirmForm
from .views import *
# from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^login$', LoginView.as_view(), name = "login"),
    url(r'^logout$', LogoutView.as_view(), name = "logout"),
    url(r'^register$', RegisterView.as_view(), name = "register"),
    url(r'^user/list$', UserList.as_view(), name = "user_list"),
    url(r'^user/update/(?P<pk>\d+)$', RegisterUpdate.as_view(), name = "user_update"),
    url(r'^user/(?P<pk>\d+)$', PerfilDetail.as_view(), name = "user_detail"),
    url(r'^user/ubicacion-list/(?P<pk>\d+)$', UbicacionList.as_view(), name = "ubicacion_list"),
    url(r'^jefes/list$', JefesList.as_view(), name = "jefes_list"),
    url(r'^mensajes/list$', MensajesList.as_view(), name = "mensajes_list"),
    url(r'^mensajes/(?P<pk>\d+)$$', MensajesDetail.as_view(), name = "mensajes_detail"),
    url(r'^password/reset/$', password_reset,
        {'post_reset_redirect': '/password/done/',
         'template_name': 'user.reset.html', 'password_reset_form':PasswordResetForm}, name="reset"),
    url(r'^password/done/$', password_reset_done,
        {'template_name': 'user.passwordreset.done.html'},
        name='reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'user.passwordreset.confirm.html', 'set_password_form':PasswordConfirmForm,
         'post_reset_redirect': '/password/end/'},
        name='password_reset_confirm'),
    url(r'^password/end/$', password_reset_done,
        {'template_name': 'user.passwordreset.end.html'},
        name='reset_end'),
    # url(r'^api/docs/', include_docs_urls(title='My API title', public=False))
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
	"""!
	Clase que gestiona el modelo perfil de usuario

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 11-10-17
	"""

	# Nombre de la empresa
	nombre_empresa = models.CharField(max_length=80)

	# Id del usuario en onesignal
	onesignal_id = models.CharField(max_length=50,null=True, blank=True)

	# Campo para el número de télefono
	# telefono = models.CharField(max_length=50, blank=True, null=True)

	# Relación con el usuario
	user = models.OneToOneField(User)
	is_online = models.BooleanField(default=False)
	# telefono = models.CharField(max_length=50, null=True, blank=True)

	def __str__(self):
		"""!
		Metodo que muestra el objeto perfil como un str

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 13-10-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@return Retorna el str del perfil
		"""
		return str(self.user.username)

from servicios.models import Servicio

class Ubicacion(models.Model):
	"""
	Clase que gestiona la localización enviada por la app

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 11-10-17
	"""

	# Latitud de la ubicación
	latitud = models.CharField(max_length=50)

	# Longitud de la ubicación
	longitud = models.CharField(max_length=50)

	# Fecha y tiempo de envío
	fecha = models.DateTimeField(auto_now=True)

	# Usuario del que se rastrea la ubicación
	usuario = models.ForeignKey(Perfil)

	formatted_address = models.CharField(max_length=250, blank=True, null=True)

	# Relación con el servicio
	# servicio = models.ForeignKey(Servicio, blank=True, null=True)

	def __str__(self):
		"""!
		Metodo que muestra el objeto alerta como un str

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 17-10-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@return Retorna el str del alerta
		"""
		return str("Ubicación - "+self.usuario.user.username+" ")+str(self.fecha)

class Mensaje(models.Model):
	"""
	Clase que los mensajes enviados

	@author Rodrigo Boet (rudmanmrrod at gmail)
	@date 12-11-17
	"""
	# Cuerpo del mensaje
	mensaje = models.TextField()

	# Usuario que envía el mensaje
	usuario = models.ForeignKey(Perfil)

	# Fecha de envio del mensaje
	fecha = models.DateTimeField(auto_now=True)

	def __str__(self):
		"""!
		Metodo que muestra el objeto mensaje como un str

		@author Rodrigo Boet (rudmanmrrod at gmail)
		@date 12-11-2017
		@param self <b>{object}</b> Objeto que instancia la clase
		@return Retorna el str del mensaje
		"""
		return str("Mensaje - "+self.usuario.user.username+" ")+str(self.fecha)

usuarios/forms.py
from django import forms
from django.forms import ModelForm
from django.core.validators import MinValueValidator
from django.contrib.auth import authenticate
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms.fields import (
    CharField, BooleanField
)
from django.forms.widgets import (
    PasswordInput, CheckboxInput, Select
)
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from .models import Perfil
from base.functions import validate_email

class LoginForm(forms.Form):
    """!
    Clase del formulario de logeo

    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 01-03-2017
    """
    ## Campo de la constraseña
    contrasena = CharField()

    ## Nombre del usuario
    usuario = CharField()

    ## Formulario de recordarme
    remember_me = BooleanField()


    def __init__(self, *args, **kwargs):
        """!
        Metodo que sobreescribe cuando se inicializa el formulario

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param args <b>{list}</b> Lista de los argumentos
        @param kwargs <b>{dict}</b> Diccionario con argumentos
        @return Retorna el formulario validado
        """
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['contrasena'].widget = PasswordInput()
        self.fields['contrasena'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Contraseña'})
        self.fields['usuario'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Nombre de Usuario'})
        self.fields['remember_me'].label = "Recordar"
        self.fields['remember_me'].widget = CheckboxInput()
        self.fields['remember_me'].required = False

    def clean(self):
        """!
        Método que valida si el usuario a autenticar es valido

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 21-04-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con los errores
        """
        usuario = self.cleaned_data['usuario']
        contrasena = self.cleaned_data['contrasena']
        usuario = authenticate(username=usuario,password=contrasena)
        if(not usuario):
            msg = "Verifique su usuario o contraseña"
            self.add_error('usuario', msg)

    class Meta:
        fields = ('usuario', 'contrasena', 'remember_me')


class UserRegisterForm(UserCreationForm):
    """!
    Formulario de Registro

    @author Rodrigo Boet (rudmanmrrod at gmail)
    @date 20-04-2017
    """
    def __init__(self, *args, **kwargs):
        """!
        Metodo que sobreescribe cuando se inicializa el formulario

        @author Rodrigo Boet (rudmanmrrod at gmail)
        @copyright GNU/GPLv2
        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param args <b>{list}</b> Lista de los argumentos
        @param kwargs <b>{dict}</b> Diccionario con argumentos
        @return Retorna el formulario validado
        """
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Nombre de usuario'})
        self.fields['username'].required = True
        self.fields['username'].label = "Nombre de Usuario"
        self.fields['password1'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Contraseña'})
        self.fields['password1'].required = True
        self.fields['password1'].label = "Contraseña"
        self.fields['password2'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Repite la Contraseña'})
        self.fields['password2'].required = True
        self.fields['password2'].label = "Repita su contraseña"
        self.fields['email'].widget.attrs.update({'class': 'form-control',
        'placeholder': 'Email'})
        self.fields['email'].required = True
        self.fields['email'].label = "Correo"

    ## nombre de la empresa
    nombre_empresa = forms.CharField(max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre de la Empresa'}),
        label="Nombre de la Empresa"
        )

    ## Tipo de Usuario
    group = forms.ModelChoiceField(
        widget=forms.Select(attrs={'class':'form-control','onchange':'register_show(this.value)'}),
        label="Tipo de Usuario", queryset=Group.objects.all(),
        empty_label = "Seleccione un tipo de usuario..."
        )

    ## Parte de servicios

    # kilometraje
    kilometraje = forms.FloatField(
        widget=forms.NumberInput(attrs={'class':'form-control','placeholder': 'Km'}),
        required = False, validators=[MinValueValidator(1)], label = 'Perimetro'
        )

    # Velocidad
    velocidad = forms.FloatField(
        widget=forms.NumberInput(attrs={'class':'form-control','placeholder': 'Límite de Velocidad (Km/h)'}),
        required = False, validators=[MinValueValidator(1)]
        )

    # Telefono
    telefono = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Télefono'}),
        required = False
        )

    # Frecuencia de Rastreo
    frecuencia_rastreo = forms.CharField(
        widget = forms.Select(attrs={'class':'form-control'},choices=(('','Seleccione un valor...'),('5','5'),('10','10'),('15','15'),('30','30'))),
        label = "Frecuencia de Rastreo (mínutos)", required = False
        )
     

    # Listado de guardias 
    guardias = forms.ModelChoiceField(
        widget=forms.Select(attrs={'class':'form-control'}),
        queryset = Perfil.objects.filter(user__groups=3).all(),
        label="Jefe de Seguridad",required = False,
        empty_label = "Seleccione un jefe de seguridad..."
        )

    # Latitud inicial
    latitud_inicial = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Latitud','readonly':True}),
        required = False
        )

    # Longitud
    longitud_inicial = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Longitud','readonly':True}),
        required = False
        )

    # Notificación
    notificacion = forms.BooleanField(required = False, label="¿Recibir Notificaciones?")


    def clean_email(self):
        """!
        Método que valida si el correo es única
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 01-03-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        email = self.cleaned_data['email']
        if(validate_email(email)):
            raise forms.ValidationError("El correo ingresado ya existe")
        return email

    def clean_kilometraje(self):
        """!
        Método que valida el kilometraje
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 08-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']
        kilometraje = self.cleaned_data['kilometraje']
        if(group.id!=1 and kilometraje==''):
            raise forms.ValidationError("Este campo es requerido")
        return kilometraje

    def clean_velocidad(self):
        """!
        Método que valida la velocidad
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 14-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']
        velocidad = self.cleaned_data['velocidad']
        if(group.id!=1 and velocidad==''):
            raise forms.ValidationError("Este campo es requerido")
        return velocidad

    def clean_telefono(self):
        """!
        Método que valida el telefono
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 08-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']
        telefono = self.cleaned_data['telefono']
        if(group.id!=1 and telefono==''):
            raise forms.ValidationError("Este campo es requerido")
        return telefono

    def clean_frecuencia_rastreo(self):
        """!
        Método que valida el frecuencia de rastreo
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 08-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']
        frecuencia_rastreo = self.cleaned_data['frecuencia_rastreo']
        if(group.id!=1 and frecuencia_rastreo==''):
            raise forms.ValidationError("Este campo es requerido")
        return frecuencia_rastreo

    def clean_latitud_inicial(self):
        """!
        Método que valida la latitud inicial
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 14-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']
        latitud_inicial = self.cleaned_data['latitud_inicial']
        if(group.id!=1 and latitud_inicial==''):
            raise forms.ValidationError("Este campo es requerido")
        return latitud_inicial

    def clean_longitud_inicial(self):
        """!
        Método que valida la longitud inicial
    
        @author Rodrigo Boet (rudmanmrrod at gmail)
        @date 14-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna el campo con la validacion
        """
        group = self.cleaned_data['group']

usuarios/templates/jefes.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Listado de Jefes de Seguridad{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Listado de Jefes de Seguridad</h1><br/>
		{% if object_list %}
			<table class="table table-responsive table-striped">
				<thead>
					<tr >
						<th class="text-center">Nombre de Usuario</th>
						<th class="text-center">Correo</th>
						<th class="text-center">Tipo de Usuario</th>
						<th class="text-center">Nombre de Empresa</th>
						<th class="text-center">Activo</th>
						<th class="text-center">Parientes</th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
						<tr>
							<td>{{ object.user.username }}</td>
							<td>{{ object.user.email }}</td>
							<td>{{ object.user.groups.all.0 }}</td>
							<td>{{ object.nombre_empresa }}</td>
							<td>{% if object.user.is_active %}Si{% else %} No {% endif%} </td>
							<td>
								<a href="{% url 'guardias_asignados_list' object.id %}">
									<i class="fa fa-group" aria-hidden="true"></i> 
								Ver</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include 'base.paginator.html' with paginator=page_obj %}
		{% else %}
		    <div class="alert alert-warning" role="alert">
	            No se encontraron registros de Jefes de Seguridad 
	        </div>
		{% endif %}
	</div>
{% endblock %}

usuarios/templates/mensajes.detail.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Detalle de Mensaje{% endblock %}
{% block content %}
	<div class="text-center">
		<div class="card">
		  <div class="card-block">
		    <h4 class="card-title">Mensaje</h4>
		    <div class="card-text">
		    	<ul class="list-group list-group-flush">
		    		<li class="list-group-item"><b>Usuario: </b>			
		    			{{ object.usuario.user.username }}
					</li>
		    		<li class="list-group-item"><b>Mensaje: </b>{{ object.mensaje }}</li>
		    		<li class="list-group-item"><b>Fecha: </b>{{ object.fecha }}</li>
		    		
		    	</ul>
		    </div>
		  </div>
		</div>
	</div>
{% endblock %}

usuarios/templates/mensajes.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Listado de Mensajes{% endblock %}
{% block content %}
	<div class="text-center">
		<h1>Listado de Mensajes</h1><br/>
		<form action="" method="get">
			<div class="row">
				<div class="col-md-5">
					{{ filter.form.username.label }}
					{{ filter.form.username }}		
				</div>
				<div class="col-md-7">
					{{ filter.form.rango_fecha.label }}
					<div class="form-inline d-flex justify-content-center">
						{{ filter.form.rango_fecha }}
					</div>
				</div>

			</div><br/>
	        <button class="btn btn-primary" type="submit">Buscar</button>
	    </form><br/>
		{% if object_list %}
			<table class="table table-responsive table-striped">
				<thead>
					<tr >
						<th class="text-center">Nombre de Usuario</th>
						<th class="text-center">Mensaje</th>
						<th class="text-center">Fecha</th>
					</tr>
				</thead>
				<tbody>
					{% for object in object_list %}
						<tr>
							<td>{{ object.usuario.user.username }}</td>
							<td>{{ object.mensaje }}</td>
							<td>{{ object.fecha }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% include 'base.paginator.html' with paginator=page_obj %}
		{% else %}
		    <div class="alert alert-warning" role="alert">
	            No se encontraron registros de Mensajes 
	        </div>
		{% endif %}
	</div>
{% endblock %}
{% block extraJs %}
	<script type="text/javascript">
	$('#id_rango_fecha_0').datepicker({
	    format: 'yyyy-mm-dd',
	    language: 'es'
	});
	$('#id_rango_fecha_1').datepicker({
	    format: 'yyyy-mm-dd',
	    language: 'es'
	});
	</script>
{% endblock %}

usuarios/templates/user.register.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Registrarse{% endblock %}
{% block content %}
  <div class="text-center">
    <h1>Registro de Usuarios</h1><hr>
    <form action="{% url 'register' %}" method="post">
    {% csrf_token %}

      <div class="form-group row {% if form.username.errors %}is-invalid{% endif %}">
          <label for="{{ form.username.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.username.label }}
          </label>
          <div class="col-sm-10">
            {{ form.username }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>

      <div class="form-group row {% if form.email.errors %}is-invalid{% endif %}">
          <label for="{{ form.email.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.email.label }}
          </label>
          <div class="col-sm-10">
            {{ form.email }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>

      <div class="form-group row {% if form.password1.errors %}is-invalid{% endif %}">
          <label for="{{ form.password1.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.password1.label }}
          </label>
          <div class="col-sm-10">
            {{ form.password1 }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.password2.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>

      <div class="form-group row {% if form.password2.errors %}is-invalid{% endif %}">
          <label for="{{ form.password2.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.password2.label }}
          </label>
          <div class="col-sm-10">
            {{ form.password2 }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.password2.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>
          
      <div class="form-group row {% if form.nombre_empresa.errors %}is-invalid{% endif %}">
          <label for="{{ form.nombre_empresa.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.nombre_empresa.label }}
          </label>
          <div class="col-sm-10">
            {{ form.nombre_empresa }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.nombre_empresa.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>

      <div class="form-group row {% if form.group.errors %}is-invalid{% endif %}">
          <label for="{{ form.group.auto_id }}" class="col-sm-2 col-form-label">
            {{ form.group.label }}
          </label>
          <div class="col-sm-10">
            {{ form.group }}
          </div>
          {% include 'base.forms.errors.html' with form_errors=form.group.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
      </div><br/>

      <div id="servicio" style="display:none;">

        <h4>Servicio</h4><br/>

        <div class="form-group row {% if form.kilometraje.errors %}is-invalid{% endif %}">
            <label for="{{ form.kilometraje.auto_id }}" class="col-sm-2 col-form-label">
              {{ form.kilometraje.label }}
            </label>
            <div class="col-sm-10">
              {{ form.kilometraje }}
            </div>
            {% include 'base.forms.errors.html' with form_errors=form.kilometraje.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
        </div><br/>


        <div class="form-group row {% if form.velocidad.errors %}is-invalid{% endif %}">
            <label for="{{ form.velocidad.auto_id }}" class="col-sm-2 col-form-label">
              {{ form.velocidad.label }}
            </label>
            <div class="col-sm-10">
              {{ form.velocidad }}
            </div>
            {% include 'base.forms.errors.html' with form_errors=form.velocidad.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
        </div><br/>

        <div class="form-group row {% if form.telefono.errors %}is-invalid{% endif %}">
            <label for="{{ form.telefono.auto_id }}" class="col-sm-2 col-form-label">
              {{ form.telefono.label }}
            </label>
            <div class="col-sm-10">
              {{ form.telefono }}
            </div>
            {% include 'base.forms.errors.html' with form_errors=form.telefono.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
        </div><br/>

        <div class="form-group row {% if form.frecuencia_rastreo.errors %}is-invalid{% endif %}">
            <label for="{{ form.frecuencia_rastreo.auto_id }}" class="col-sm-2 col-form-label">
              {{ form.frecuencia_rastreo.label }}
            </label>
            <div class="col-sm-10">
              {{ form.frecuencia_rastreo }}
            </div>
            {% include 'base.forms.errors.html' with form_errors=form.frecuencia_rastreo.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
        </div><br/>

        <div id="guardia" style="display:none;">
          <div class="form-group row {% if form.guardias.errors %}is-invalid{% endif %}">
              <label for="{{ form.guardias.auto_id }}" class="col-sm-2 col-form-label">
                {{ form.guardias.label }}
              </label>
              <div class="col-sm-10">
                {{ form.guardias }}
              </div>
              {% include 'base.forms.errors.html' with form_errors=form.guardias.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
          </div><br/>

            <div class="form-group row {% if form.notificacion.errors %}is-invalid{% endif %}">
              <label for="{{ form.notificacion.auto_id }}" class="col-sm-2 col-form-label">
                {{ form.notificacion.label }}
              </label>
              <div class="col-sm-10">
                {{ form.notificacion }}
              </div>
              {% include 'base.forms.errors.html' with form_errors=form.notificacion.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
          </div><br/>
        </div>

        <div id="map" style="height: 400px;width: 100%;"></div>

        <div class="row">
          <div class="col-md-6 {% if form.latitud_inicial.errors %}is-invalid{% endif %}">
              <label for="{{ form.latitud_inicial.auto_id }}" class="col-form-label">
                {{ form.latitud_inicial.label }}
              </label>
              {{ form.latitud_inicial }}
              {% include 'base.forms.errors.html' with form_errors=form.latitud_inicial.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
          </div>
          <div class="col-md-6 {% if form.longitud_inicial.errors %}is-invalid{% endif %}">
              <label for="{{ form.longitud_inicial.auto_id }}" class="col-form-label">
                {{ form.longitud_inicial.label }}
              </label>
              {{ form.longitud_inicial }}
              {% include 'base.forms.errors.html' with form_errors=form.longitud_inicial.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
          </div>
        </div><br/>

      </div>


      <div>
         <button type="submit" class="btn btn-success">Registrarse</button>
      </div>
    </form>

  </div>
  <br />
{% endblock %}
{% block extraJs %}
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCB2JmjC8UmVNtWXAUIMkhYG1_xf0QKrzI&callback=load_google_map"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      register_show($('#id_group').val());
    });
  </script>
{% endblock %}